document: feedback-pipeline-workload
version: 1
data:
  name: RHEL packager
  description: ELN Extras packages for RHEL maintainers
  maintainer: rhel-sst-cpe
  packages:
    - NetworkManager-openvpn-gnome
    - centpkg
  labels:
    - eln-extras
